name: CyberSentinel Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      - name: Type check
        run: npm run typecheck
        
      - name: Run tests
        run: npm test
        
      - name: Security audit
        run: npm run security:audit
        
      - name: Build
        run: npm run build

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: quality
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Dependency Check
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              execSync('npx audit-ci --moderate');
              console.log('✅ No security vulnerabilities found');
            } catch (error) {
              console.log('⚠️ Security vulnerabilities found:');
              console.log(error.stdout.toString());
              core.setFailed('Security vulnerabilities must be addressed');
            }
            
      - name: SAST Scan
        uses: github/codeql-action/analyze@v3
